JPhukanSF/trigger-worflow

force-app/main/default/objects/Account/fields/work_item_1_test__c.field-meta.xml

[DevOps Center] Merge WI-000004 to Integration

---

force-app/main/default/objects/Account/fields/test_field2__c.field-meta.xml

[DevOps Center] Merge WI-000005 to Integration

---

force-app/main/default/objects/Account/fields/test_field3__c.field-meta.xml

[DevOps Center] Merge WI-000006 to Integration

---

force-app/main/default/objects/Account/fields/test_field4__c.field-meta.xml

[DevOps Center] Merge WI-000007 to Integration

---

force-app/main/default/objects/Account/fields/test_field4__c.field-meta.xml

[DevOps Center] Merge WI-000007 to UAT

---

force-app/main/default/objects/Account/fields/test_field3__c.field-meta.xml

[DevOps Center] Merge WI-000006 to UAT

---

force-app/main/default/objects/Account/fields/test_field2__c.field-meta.xml

[DevOps Center] Merge WI-000005 to UAT

---

force-app/main/default/objects/Account/fields/test_field2__c.field-meta.xml
force-app/main/default/objects/Account/fields/test_field3__c.field-meta.xml
force-app/main/default/objects/Account/fields/test_field4__c.field-meta.xml
force-app/main/default/objects/Account/fields/work_item_1_test__c.field-meta.xml

DevOps Center created this pull request for DevOps Center use only. Due to the potential for data corruption, DO NOT MERGE this pull request in GitHub.

[DO NOT MERGE] For DevOps Center use only - Integration to UAT

---

force-app/main/default/objects/Account/fields/work_item_1_test__c.field-meta.xml

[DevOps Center] Merge WI-000004 to UAT

---

force-app/main/default/objects/Account/fields/test_field11__c.field-meta.xml

[DevOps Center] Merge WI-000008 to Integration

---

force-app/main/default/objects/Account/fields/test_field__c.field-meta.xml

[DevOps Center] Merge WI-000000 to Integration

---

force-app/main/default/objects/Account/Account.object-meta.xml
force-app/main/default/objects/Account/fields/test_field__c.field-meta.xml

[DevOps Center] Merge WI-000004 to devopsquality

---

force-app/main/default/objects/Account/Account.object-meta.xml
force-app/main/default/objects/Account/fields/test_field__c.field-meta.xml

DevOps Center created this change request for DevOps Center use only. Due to the potential for data corruption, DO NOT MERGE this change request.

[DO NOT MERGE] For DevOps Center use only - devopsquality to Production

---

force-app/main/default/objects/Account/Account.object-meta.xml
force-app/main/default/objects/Account/fields/test_field__c.field-meta.xml

[DevOps Center] Merge WI-000004 to Production

---

force-app/main/default/objects/Account/fields/eeeeee__c.field-meta.xml

[DevOps Center] Merge WI-000007 to devopsquality

---

force-app/main/default/objects/Account/fields/abc__c.field-meta.xml

[DevOps Center] Merge WI-000009 to devopsquality

---

force-app/main/default/objects/Account/fields/demo_field__c.field-meta.xml

[DevOps Center] Merge WI-000000 to UAT devopsQuality

---

force-app/main/default/objects/Account/fields/test_sr__c.field-meta.xml

[DevOps Center] Merge WI-000001 to UAT devopsQuality

---

force-app/main/default/objects/Account/fields/demo_field__c.field-meta.xml
force-app/main/default/objects/Account/fields/test_sr__c.field-meta.xml

[DevOps Center] Merge UAT devopsQuality to Staging mp

---

force-app/main/default/objects/Account/fields/demo1__c.field-meta.xml

[DevOps Center] Merge WI-000005 to UAT devopsQuality

---

force-app/main/default/objects/Account/fields/demo1__c.field-meta.xml

DevOps Center created this change request for DevOps Center use only. Due to the potential for data corruption, DO NOT MERGE this change request.

[DO NOT MERGE] For DevOps Center use only - UAT devopsQuality to Production

---

force-app/main/default/objects/Account/fields/demo1__c.field-meta.xml

[DevOps Center] Merge WI-000005 to Production

---

force-app/main/default/objects/Activity/Activity.object-meta.xml
force-app/main/default/objects/Activity/fields/demo2__c.field-meta.xml

[DevOps Center] Merge WI-000007 to UAT devopsQuality
